[package]
name = "main-for-processbot-staging"
version = "0.1.0"
authors = ["paritytech <info@parity.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
